server:
  port: 8081

person:
    lastName: hellonihao
    age: 20
    boss: false
    birth: 2019/10/12
    map: {k1: v1,k2: v2}
    list:
        - lisi
        - wangwu
    dog:
        name: 小狗
        age: 2